commit
dolphin-vr/watch-spot pull request #3
Opened 2023-04-20 19:02 UTC by DmitrFr

пробний

2023-04-20 19:14 UTC, DmitrFr commented
На разі Хедер не має абсолютного позиціювання, також проблеми з SVG

2023-04-20 20:39 UTC, dolphin-vr requested changes
простав коми

2023-04-20 20:39 UTC, dolphin-vr commented on src/css/header.css
> +   font-family: 'Epilogue' sans-serif;
font-family: 'Epilogue', sans-serif;
пропустив кому

2023-04-20 20:39 UTC, dolphin-vr commented on src/css/header.css
> +   font-family: 'Epilogue' sans-serif;
font-family: 'Epilogue', sans-serif;
пропустив кому

2023-04-20 20:39 UTC, dolphin-vr commented on src/css/header.css
> +      font-family: 'Epilogue' sans-serif;
font-family: 'Epilogue', sans-serif;
пропустив кому

2023-04-21 11:43 UTC, dolphin-vr approved these changes

2023-04-21 11:47 UTC, merged