new-watch
dolphin-vr/watch-spot pull request #4
Opened 2023-04-20 21:13 UTC by oleg-mahnichev

Розмітка повинна працювати, ефекти на картки ще ніякі не додавав

2023-04-20 21:35 UTC, dolphin-vr requested changes
помилка в цсс

2023-04-20 21:35 UTC, dolphin-vr commented on src/css/novelty.css
> +margin: bottom 8px; ;
margin-bottom мабуть

2023-04-21 08:21 UTC, oleg-mahnichev commented on src/css/novelty.css
> +margin: bottom 8px; ;
так і є, виправив. Що робити ? заново пушити і мерджити ?

2023-04-21 09:01 UTC, dolphin-vr commented on src/css/novelty.css
> +margin: bottom 8px; ;
Заново комітити і пушити. Мержити вже я буду :)

2023-04-21 09:04 UTC, dolphin-vr approved these changes

2023-04-21 09:04 UTC, merged